//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StPlanning.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBsc
    {
        public long Id { get; set; }
        public long IdProject { get; set; }
        public Nullable<int> MainLevel { get; set; }
        public Nullable<int> Type { get; set; }
        public string Perspective { get; set; }
        public string ValueSt { get; set; }
        public string StObjectives { get; set; }
        public string Kpis { get; set; }
        public string OpDefinition { get; set; }
        public string ActuationFreq { get; set; }
        public string CaptDataFreq { get; set; }
        public string Levels { get; set; }
        public string Goal { get; set; }
        public string RedVar { get; set; }
        public string YellVar { get; set; }
        public string GreVar { get; set; }
        public string GoalResp { get; set; }
        public string StInitiative { get; set; }
        public string ImpleResp { get; set; }
        public Nullable<System.DateTime> DateInit { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        public virtual tblProject tblProject { get; set; }
    }
}
