//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StPlanning.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFoda
    {
        public tblFoda()
        {
            this.tblFodaDetail = new HashSet<tblFodaDetail>();
        }
    
        public long Id { get; set; }
        public long IdProject { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string UserInsert { get; set; }
        public string ComputerInsert { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
        public string UserUpdate { get; set; }
        public string ComputerUpdate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    
        public virtual ICollection<tblFodaDetail> tblFodaDetail { get; set; }
        public virtual tblProject tblProject { get; set; }
    }
}
