//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StPlanning.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject
    {
        public tblProject()
        {
            this.tblBsc = new HashSet<tblBsc>();
            this.tblDa = new HashSet<tblDa>();
            this.tblDiagram = new HashSet<tblDiagram>();
            this.tblDo = new HashSet<tblDo>();
            this.tblFa = new HashSet<tblFa>();
            this.tblFo = new HashSet<tblFo>();
            this.tblFoda = new HashSet<tblFoda>();
            this.tblManagerSt = new HashSet<tblManagerSt>();
            this.tblStrategiesBasic = new HashSet<tblStrategiesBasic>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Vision { get; set; }
        public string Description { get; set; }
        public bool FodaUpload { get; set; }
        public bool FoUpload { get; set; }
        public bool DoUpload { get; set; }
        public bool FaUpload { get; set; }
        public bool DaUpload { get; set; }
        public bool StrategiesBasicUpload { get; set; }
        public bool StrategiesManagerUpload { get; set; }
        public bool StrategiesLevel2Upload { get; set; }
        public bool StrategiesLevel3Upload { get; set; }
        public bool StrategiesLevel4Upload { get; set; }
        public bool DiagramPrivateUpload { get; set; }
        public bool DiagramPublicUpload { get; set; }
        public bool BscUpload1 { get; set; }
        public bool BscUpload2 { get; set; }
        public bool BscUpload3 { get; set; }
        public bool BscUpload4 { get; set; }
        public bool BscPubUpload1 { get; set; }
        public bool BscPubUpload2 { get; set; }
        public bool BscPubUpload3 { get; set; }
        public bool BscPubUpload4 { get; set; }
        public string UserInsert { get; set; }
        public string ComputerInsert { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
        public string UserUpdate { get; set; }
        public string ComputerUpdate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    
        public virtual ICollection<tblBsc> tblBsc { get; set; }
        public virtual ICollection<tblDa> tblDa { get; set; }
        public virtual ICollection<tblDiagram> tblDiagram { get; set; }
        public virtual ICollection<tblDo> tblDo { get; set; }
        public virtual ICollection<tblFa> tblFa { get; set; }
        public virtual ICollection<tblFo> tblFo { get; set; }
        public virtual ICollection<tblFoda> tblFoda { get; set; }
        public virtual ICollection<tblManagerSt> tblManagerSt { get; set; }
        public virtual ICollection<tblStrategiesBasic> tblStrategiesBasic { get; set; }
    }
}
