//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StPlanning.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStrategiesBasic
    {
        public long Id { get; set; }
        public long IdProject { get; set; }
        public string Type { get; set; }
        public string Crossed { get; set; }
        public string Strategy { get; set; }
        public Nullable<int> Color { get; set; }
        public string Level { get; set; }
        public string UserInsert { get; set; }
        public string ComputerInsert { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
        public string UserUpdate { get; set; }
        public string ComputerUpdate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<bool> Finished { get; set; }
    
        public virtual tblProject tblProject { get; set; }
    }
}
